name: ChostPulse
version: 1.0.0
api: 5.30.0
main: ChernegaSergiy\ChostPulse\Main
author: ChernegaSergiy
description: Decentralized server monitoring via Cloudflare Workers
website: https://github.com/ChernegaSergiy/chost-pulse

permissions:
  chostpulse.admin:
    description: Allows managing plugin configuration
    default: op
